### ISSUE TITLE
Undefined offset: 2

### ISSUE THREAD

**Issue by jakub-rompca** [Eden-PHP/Mail#13]
When downloading certain emails "in vendor/eden/mail/src/Imap.php at line 1371".
Here's what imap pushes to Eden
array('header' => '', 'headers' => object(stdClass), 'tos' => array(), 'ccs' => array(), 'bccs' => array(), 'ID' => array())
Annoying since i cannot download whole mailbox that contains less than 90 mails.

**Comment by wolf3r** [comment]
function imap_rfc822_parse_headers($header)
 in imap.php

If htmlentities (line 1367) shits itself on, for example, mails that were denied by x-spam all hell breaks loose.

**Comment by soycaringal** [comment]
@wolf3r Can you please provide a screenshot of your error?

**Comment by amirgee007** [comment]
![image](https://cloud.githubusercontent.com/assets/16411441/20298585/89e95c1e-ab38-11e6-9352-f1b131d13473.png)

**Comment by amirgee007** [comment]
is there any way to minimize it??
