### ISSUE TITLE
Illegal string offset 'messages'

### ISSUE THREAD

**Issue by SharKing-Lin** [Eden-PHP/Mail#19]
Is this some bug? Or you're missing something?
![screenshot_1](https://cloud.githubusercontent.com/assets/5708248/16705878/5e04dff0-45c2-11e6-81a0-579cad0eaf9b.png)
Last time i checked, i dont thing u need to put "$total = $total['messages'];" on there anymore, cause you have return some number on getEmailTotal function.
![screenshot_4](https://cloud.githubusercontent.com/assets/5708248/16705880/765ed254-45c2-11e6-90e3-86fa79600b78.png)
Sorry for my bad English, btw i like your project..

**Comment by Schnoffel** [comment]
It is a bug, because there is no index 'messages'. The method getEmailTotal() returns an integer, the total number of emails.

Workaround seems to comment it out:

`#$total = $total['messages'];`

**Comment by cblanquera** [comment]
Hello, just acknowledging this one. I will assign it to someone on the team. Thanks!

**Comment by adin234** [comment]
@cblanquera i think there is already a pull request created for this https://github.com/Eden-PHP/Mail/pull/17/files

**Comment by sommcz** [comment]
please, can you accept pull request mentioned above - pop3 client is unusable due to this bug.
thanx

**Comment by sommcz** [comment]
please, can you accept pull request mentioned above - pop3 client is unusable due to this bug (and not passing tests).
thanx
