### ISSUE TITLE
Missing 8bit

### ISSUE THREAD

**Issue by Schnoffel** [Eden-PHP/Mail#20]
In **getParts()** of **src/Pop3.php** there is a case missing for 8 bit content transfer encoding:

8bit is already UTF-8 (as I know, but I am not 100 % sure), so not more than extending the switch is necessary:

```
switch (strtolower($head['content-transfer-encoding'])) {
    case 'binary':
        $body = imap_binary($body);
        break;
    case 'base64':
        $body = base64_decode($body);
        break;
    case 'quoted-printable':
        $body = quoted_printable_decode($body);
        break;
    case '7bit':
        $body = mb_convert_encoding($body, 'UTF-8', 'ISO-2022-JP');
        break;
    case '8bit':
        break;
    default:
        $body = str_replace(array("\n", ' '), '', $body);
        break;
}
```

**Comment by cblanquera** [comment]
Hello @Schnoffel thanks for the TLC :) ,

It might be me misunderstanding the issue, the switch formats the `$body` content in which we do not  want to do anything in the case it is already readable. So far it's working as described. Is there a particular issue you are having with this ? Sorry it's unclear.

**Comment by Schnoffel** [comment]
The default-Action was the problem at one email with 8bit. I was wondering why the email was damaged and then I saw the newlines were replaced.

Are you sure 8bit needs this replacing actions? I think it was a phpBB3 text/plain mail.

**Comment by Schnoffel** [comment]
@cblanquera I added more evidence now for better explaination of the problem.
