### ISSUE TITLE
getParts() fails in some cases

### ISSUE THREAD

**Issue by Schnoffel** [Eden-PHP/Mail#21]
The function **getParts()** of **src/Pop3.php** fails when some header information is not written in lowercase, like **Boundary=...** instead of **boundary=...**.

Solution is to replace

`$extra[$key] = $value;`

with

`$extra[strtolower($key)] = $value;`

```
//foreach extra
foreach ($extra as $i => $attr) {
    //transform the extra array to a key value pair
    $attr = explode('=', $attr, 2);
    if (count($attr) > 1) {
        list($key, $value) = $attr;
        $extra[strtolower($key)] = $value;
    }
    unset($extra[$i]);
}
```

**Comment by cblanquera** [comment]
Thanks @Schnoffel We are looking into the matter
