### ISSUE TITLE
Notice: Undefined variable: code in vendor\eden\core\src\Argument.php on line 54

### ISSUE THREAD

**Issue by netbasejsc** [Eden-PHP/Mail#44]
Hello,

After I installed the latest version via composer and  run 
`$database = eden('mysql', '[HOST]' ,'[DBNAME]', '[USER]', '[PASS]'); //instantiate`
I get a msg:
Fatal error: Call to undefined function eden() in /index.php on line 
I search this error on google and see this issues https://github.com/Eden-PHP/Mysql/issues/1
I add Eden::DECORATOR; after require autoload

`require_once __DIR__.'/vendor/autoload.php';
Eden::DECORATOR;`
And I get a new php error:
```
Notice: Undefined variable: message in D:\HomeServer\htdocs\phpdemo\mail\vendor\eden\core\src\Argument.php on line 54

Notice: Undefined variable: code in D:\HomeServer\htdocs\phpdemo\mail\vendor\eden\core\src\Argument.php on line 54
```
Please help me, thanks!

**Comment by smartcatdev** [comment]
im seeing the same notice.

``` PHP
    public static function i()
    {
        $class = __CLASS__;
        return new $class($message, $code);
    }
```

**Comment by smartcatdev** [comment]
this is in Eden 4.0.2 btw

**Comment by cblanquera** [comment]
wrong project?

**Comment by shahmir811** [comment]
Getting the same error ...
Someone will kindly work on it...
